import { Member, MemberStatus, News, Complaint, EmergencyDirective, RoleDefinition, SectionDefinition, SPPD, SPPDReport, JabatanDefinition, FinancialTransaction, ReimbursementRequest } from './types';

export const INITIAL_ROLES: RoleDefinition[] = [
  { id: 'admin', name: 'Admin', isSystem: true },
  { id: 'pimpinan', name: 'Pimpinan', isSystem: true },
  { id: 'sekretaris', name: 'Sekretaris', isSystem: true },
  { id: 'bendahara', name: 'Bendahara', isSystem: true },
  { id: 'kepala-seksi', name: 'Kepala Seksi', isSystem: true },
  { id: 'operator', name: 'Operator', isSystem: true },
  { id: 'anggota', name: 'Anggota', isSystem: true },
];

export const INITIAL_SECTIONS: SectionDefinition[] = [
  { id: 'pimpinan', name: 'Pimpinan', isSystem: true },
  { id: 'sekretariat', name: 'Sekretariat', isSystem: true },
  { id: 'keuangan', name: 'Keuangan', isSystem: true },
  { id: 'logistik', name: 'Logistik', isSystem: false },
  { id: 'evakuasi', name: 'Evakuasi', isSystem: false },
  { id: 'humas', name: 'Humas', isSystem: false },
  { id: 'umum', name: 'Umum', isSystem: false },
];

export const INITIAL_JABATAN: JabatanDefinition[] = [
  { id: 'administrator-sistem', name: 'Administrator Sistem' },
  { id: 'pimpinan', name: 'Pimpinan' },
  { id: 'sekretaris', name: 'Sekretaris' },
  { id: 'bendahara', name: 'Bendahara' },
  { id: 'kepala-seksi-logistik', name: 'Kepala Seksi Logistik' },
  { id: 'anggota-tim-logistik', name: 'Anggota Tim Logistik' },
  { id: 'kepala-seksi-evakuasi', name: 'Kepala Seksi Evakuasi' },
  { id: 'anggota-tim-evakuasi', name: 'Anggota Tim Evakuasi' },
  { id: 'operator-humas', name: 'Operator Hubungan Masyarakat' },
];


export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'admin-user-001',
    namaLengkap: 'Admin Utama',
    nomorId: 'ADMIN001',
    tanggalLahir: '1980-01-01',
    jenisKelamin: 'Laki-laki',
    alamat: 'Kantor Pusat BNPB, Jakarta',
    telepon: '021-29827793',
    email: 'admin@bnpb.go.id',
    jabatan: 'Administrator Sistem',
    tanggalBergabung: '2024-01-01',
    status: MemberStatus.AKTIF,
    bio: 'Akun administrator utama untuk manajemen sistem.',
    fotoUrl: 'https://i.pravatar.cc/400?u=admin@bnpb.go.id',
    role: 'Admin',
    seksi: 'Pimpinan',
  },
  {
    id: 'pimpinan-user-001',
    namaLengkap: 'Jenderal Doni Monardo',
    nomorId: 'PIMPINAN001',
    tanggalLahir: '1975-05-10',
    jenisKelamin: 'Laki-laki',
    alamat: 'Jl. Pramuka Kav. 38, Jakarta Timur',
    telepon: '081234567890',
    email: 'pimpinan@bnpb.go.id',
    jabatan: 'Pimpinan',
    tanggalBergabung: '2020-02-15',
    status: MemberStatus.AKTIF,
    bio: 'Memimpin dan mengkoordinasikan upaya penanggulangan bencana nasional.',
    fotoUrl: 'https://i.pravatar.cc/400?u=pimpinan@bnpb.go.id',
    role: 'Pimpinan',
    seksi: 'Pimpinan',
  },
   {
    id: 'sekretaris-user-001',
    namaLengkap: 'Siti Nurbaya',
    nomorId: 'SEKRE001',
    tanggalLahir: '1985-08-20',
    jenisKelamin: 'Perempuan',
    alamat: 'Komplek Perkantoran, Jakarta',
    telepon: '081223344556',
    email: 'sekretaris@bnpb.go.id',
    jabatan: 'Sekretaris',
    tanggalBergabung: '2021-03-10',
    status: MemberStatus.AKTIF,
    bio: 'Mengelola administrasi dan surat-menyurat organisasi.',
    fotoUrl: 'https://i.pravatar.cc/400?u=sekretaris@bnpb.go.id',
    role: 'Sekretaris',
    seksi: 'Sekretariat',
  },
  {
    id: 'bendahara-user-001',
    namaLengkap: 'Budi Hartono',
    nomorId: 'BENDA001',
    tanggalLahir: '1982-11-30',
    jenisKelamin: 'Laki-laki',
    alamat: 'Jl. Keuangan Negara, Jakarta',
    telepon: '081334455667',
    email: 'bendahara@bnpb.go.id',
    jabatan: 'Bendahara',
    tanggalBergabung: '2022-01-20',
    status: MemberStatus.AKTIF,
    bio: 'Bertanggung jawab atas pengelolaan keuangan organisasi.',
    fotoUrl: 'https://i.pravatar.cc/400?u=bendahara@bnpb.go.id',
    role: 'Bendahara',
    seksi: 'Keuangan',
  },
  {
    id: 'kasi-evakuasi-001',
    namaLengkap: 'Mayor Asep',
    nomorId: 'KASI-EVA001',
    tanggalLahir: '1980-04-15',
    jenisKelamin: 'Laki-laki',
    alamat: 'Pusdiklat PB, Sentul',
    telepon: '081298765432',
    email: 'asep.kasi@bnpb.go.id',
    jabatan: 'Kepala Seksi Evakuasi',
    tanggalBergabung: '2019-07-21',
    status: MemberStatus.AKTIF,
    bio: 'Kepala seksi yang bertanggung jawab atas operasi evakuasi.',
    fotoUrl: 'https://i.pravatar.cc/400?u=asep.kasi@bnpb.go.id',
    role: 'Kepala Seksi',
    seksi: 'Evakuasi',
  },
  {
    id: 'operator-user-001',
    namaLengkap: 'Rina Fauziah',
    nomorId: 'OPERATOR001',
    tanggalLahir: '1992-03-12',
    jenisKelamin: 'Perempuan',
    alamat: 'Kantor Humas BNPB, Jakarta',
    telepon: '081211122233',
    email: 'operator@bnpb.go.id',
    jabatan: 'Operator Hubungan Masyarakat',
    tanggalBergabung: '2023-01-10',
    status: MemberStatus.AKTIF,
    bio: 'Operator yang menangani aduan masyarakat dan publikasi berita.',
    fotoUrl: 'https://i.pravatar.cc/400?u=operator@bnpb.go.id',
    role: 'Operator',
    seksi: 'Humas',
  },
  {
    id: 'anggota-eva-001',
    namaLengkap: 'Bambang Susilo',
    nomorId: 'ANGGOTA-EVA001',
    tanggalLahir: '1995-11-25',
    jenisKelamin: 'Laki-laki',
    alamat: 'Jl. Merdeka, Bogor',
    telepon: '085712345678',
    email: 'bambang.eva@bnpb.go.id',
    jabatan: 'Anggota Tim Evakuasi',
    tanggalBergabung: '2022-08-01',
    status: MemberStatus.AKTIF,
    bio: 'Anggota tim evakuasi lapangan, siap tanggap darurat.',
    fotoUrl: 'https://i.pravatar.cc/400?u=bambang.eva@bnpb.go.id',
    role: 'Anggota',
    seksi: 'Evakuasi',
  },
  {
    id: 'kasi-logistik-001',
    namaLengkap: 'Dewi Lestari',
    nomorId: 'KASI-LOG001',
    tanggalLahir: '1983-09-05',
    jenisKelamin: 'Perempuan',
    alamat: 'Gudang Logistik BNPB, Bekasi',
    telepon: '081345678901',
    email: 'dewi.logistik@bnpb.go.id',
    jabatan: 'Kepala Seksi Logistik',
    tanggalBergabung: '2020-05-18',
    status: MemberStatus.AKTIF,
    bio: 'Mengelola distribusi dan ketersediaan logistik bencana.',
    fotoUrl: 'https://i.pravatar.cc/400?u=dewi.logistik@bnpb.go.id',
    role: 'Kepala Seksi',
    seksi: 'Logistik',
  },
  {
    id: 'anggota-log-001',
    namaLengkap: 'Cahyo Utomo',
    nomorId: 'ANGGOTA-LOG001',
    tanggalLahir: '1993-01-15',
    jenisKelamin: 'Laki-laki',
    alamat: 'Jl. Industri, Cikarang',
    telepon: '087812345678',
    email: 'cahyo.log@bnpb.go.id',
    jabatan: 'Anggota Tim Logistik',
    tanggalBergabung: '2023-02-20',
    status: MemberStatus.TIDAK_AKTIF,
    bio: 'Anggota tim logistik yang handal dalam pendataan inventaris.',
    fotoUrl: 'https://i.pravatar.cc/400?u=cahyo.log@bnpb.go.id',
    role: 'Anggota',
    seksi: 'Logistik',
  }
];

export const INITIAL_NEWS: News[] = [
  {
    id: 'news-001',
    title: 'Peringatan Dini Tsunami di Pantai Selatan Jawa',
    content: 'BMKG mengeluarkan peringatan dini tsunami menyusul gempa berkekuatan 7.2 SR yang terjadi di lepas pantai selatan Jawa. Masyarakat di pesisir pantai dihimbau untuk waspada dan mengikuti arahan dari petugas berwenang. Tim BNPB telah dikerahkan ke lokasi untuk melakukan mitigasi dan persiapan evakuasi jika diperlukan.',
    imageUrl: 'https://images.unsplash.com/photo-1593352219757-013b52a5d7c4?q=80&w=800&auto=format&fit=crop',
    category: 'Peringatan Dini',
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
  },
  {
    id: 'news-002',
    title: 'BNPB Gelar Pelatihan Kesiapsiagaan Bencana di Sekolah',
    content: 'Dalam rangka meningkatkan kesadaran dan kesiapsiagaan sejak dini, BNPB menyelenggarakan pelatihan simulasi gempa dan kebakaran di lebih dari 50 sekolah dasar di wilayah Jabodetabek. Kegiatan ini bertujuan untuk memberikan pengetahuan praktis kepada siswa dan guru tentang cara menyelamatkan diri saat terjadi bencana.',
    imageUrl: 'https://images.unsplash.com/photo-1518495962095-2d9391035156?q=80&w=800&auto=format&fit=crop',
    category: 'Kegiatan',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
  },
];

export const INITIAL_COMPLAINTS: Complaint[] = [
    {
        id: 'comp-001',
        namaPelapor: 'Andi Wijaya',
        telepon: '081234567890',
        email: 'andi.w@example.com',
        jenisLaporan: 'Permintaan Evakuasi',
        lokasiKejadian: 'Desa Suka Maju, RT 03/RW 01, Kecamatan Sejahtera',
        content: 'Banjir bandang telah merendam desa kami. Ketinggian air sudah mencapai atap rumah. Banyak warga, terutama lansia dan anak-anak, terjebak dan membutuhkan evakuasi segera.',
        status: 'Menunggu Disposisi Pimpinan',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
        currentOwner: 'pimpinan',
    },
    {
        id: 'comp-002',
        namaPelapor: 'Siti Aminah',
        telepon: '087712345678',
        email: 'siti.a@example.com',
        jenisLaporan: 'Laporan Kerusakan Infrastruktur',
        lokasiKejadian: 'Jembatan Citarum, Jalan Raya Provinsi KM 15',
        content: 'Jembatan utama yang menghubungkan dua kecamatan retak parah akibat gempa semalam. Sangat berbahaya untuk dilintasi kendaraan. Mohon segera ditangani untuk mencegah korban jiwa.',
        status: 'Didisposisikan ke Seksi',
        timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
        currentOwner: 'logistik', 
        dispositionNotes: 'Seksi Logistik, harap segera koordinasi dengan PU untuk assessment dan penanganan darurat jembatan.',
    },
    {
        id: 'comp-003',
        namaPelapor: 'Budi Santoso',
        telepon: '',
        email: '',
        jenisLaporan: 'Permintaan Logistik & Bantuan',
        lokasiKejadian: 'Posko Pengungsian Lapangan Merdeka',
        content: 'Kebutuhan mendesak di posko pengungsian: selimut, makanan bayi, air bersih, dan obat-obatan. Stok kami menipis.',
        status: 'Baru',
        timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(), // 30 mins ago
        currentOwner: 'operator',
    },
];

export const INITIAL_DIRECTIVES: EmergencyDirective[] = [
    {
        id: 'dir-001',
        createdBy: 'pimpinan-user-001',
        title: 'Respon Cepat Banjir Bandang Desa Suka Maju',
        urgency: 'Tinggi',
        status: 'Dikerjakan',
        date: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(), // 1 hour ago
        description: 'Segera kerahkan Tim Evakuasi ke Desa Suka Maju. Prioritaskan evakuasi lansia, anak-anak, dan kelompok rentan. Koordinasi dengan Tim Logistik untuk penyediaan perahu karet dan pelampung. Laporkan perkembangan setiap jam.',
        assignedTo: ['kasi-evakuasi-001', 'kasi-logistik-001'],
    },
    {
        id: 'dir-002',
        createdBy: 'sekretaris-user-001',
        title: 'Distribusi Bantuan Logistik ke Posko Merdeka',
        urgency: 'Sedang',
        status: 'Baru',
        date: new Date().toISOString(),
        description: 'Berdasarkan laporan masuk, segera siapkan dan distribusikan bantuan berupa selimut, makanan bayi, air bersih, dan obat-obatan ke Posko Pengungsian Lapangan Merdeka. Dokumentasikan serah terima bantuan.',
        assignedTo: 'all',
    }
];

export const INITIAL_SPPDS: SPPD[] = [
    {
        id: 'sppd-001',
        nomorSurat: 'SPPD/001/BNPB/VII/2024',
        dasarHukum: 'Surat Tugas No. 123/ST/BNPB/2024',
        untuk: 'Melakukan assessment dampak dan kebutuhan pasca-bencana gempa di Cianjur.',
        tujuan: 'Kabupaten Cianjur, Jawa Barat',
        tanggalBerangkat: '2024-07-20',
        tanggalKembali: '2024-07-25',
        penerimaTugasIds: ['anggota-eva-001', 'anggota-log-001'],
        pembuatId: 'sekretaris-user-001',
        status: 'Menunggu Persetujuan',
        dibuatTanggal: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'sppd-002',
        nomorSurat: 'SPPD/002/BNPB/VII/2024',
        dasarHukum: 'Undangan Rapat Koordinasi Nasional No. 456/RAKORNAS/2024',
        untuk: 'Menghadiri Rapat Koordinasi Nasional Penanggulangan Bencana',
        tujuan: 'Hotel Grand Hyatt, Jakarta',
        tanggalBerangkat: '2024-08-01',
        tanggalKembali: '2024-08-03',
        penerimaTugasIds: ['kasi-evakuasi-001'],
        pembuatId: 'sekretaris-user-001',
        penyetujuId: 'pimpinan-user-001',
        status: 'Disetujui',
        dibuatTanggal: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        anggaranTotal: 5000000,
    }
];

export const INITIAL_SPPD_REPORTS: SPPDReport[] = [];

export const INITIAL_FINANCIAL_TRANSACTIONS: FinancialTransaction[] = [
    {
        id: 'fin-001',
        date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        description: 'Donasi dari PT. Sejahtera Abadi',
        category: 'Donasi',
        type: 'Pemasukan',
        amount: 50000000,
    },
    {
        id: 'fin-002',
        date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        description: 'Pembelian 100 paket sembako untuk korban banjir',
        category: 'Logistik',
        type: 'Pengeluaran',
        amount: 15000000,
    },
     {
        id: 'fin-003',
        date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        description: 'Biaya BBM untuk 5 unit mobil operasional',
        category: 'BBM',
        type: 'Pengeluaran',
        amount: 2500000,
    }
];

export const INITIAL_REIMBURSEMENT_REQUESTS: ReimbursementRequest[] = [
    {
        id: 'reimburse-001',
        requesterId: 'anggota-eva-001',
        requesterName: 'Bambang Susilo',
        date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        amount: 250000,
        category: 'Operasional Harian',
        description: 'Pembelian konsumsi dan air mineral untuk tim di lapangan saat evakuasi.',
        status: 'Menunggu Persetujuan',
        proofUrl: 'https://example.com/struk.jpg',
        proofName: 'struk_konsumsi.jpg',
    },
     {
        id: 'reimburse-002',
        requesterId: 'kasi-logistik-001',
        requesterName: 'Dewi Lestari',
        date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        amount: 750000,
        category: 'SPPD',
        description: 'Biaya tol dan makan selama perjalanan dinas ke Bandung.',
        status: 'Disetujui',
        proofUrl: 'https://example.com/bukti.pdf',
        proofName: 'bukti_sppd_bandung.pdf',
        approvedById: 'pimpinan-user-001',
    }
];
